### ISSUE TITLE
Not keep the list of blocked sites when you close firefox

### ISSUE THREAD

**Issue by wildskyf** [wildskyf/personal-blocklist#3]
As Marko [said](https://addons.mozilla.org/zh-TW/firefox/addon/personal-blocklist/reviews/878741/):

> Ne bloque rien dans les recherches d'images.
> 
> Hello Wildsky !
> Firstly it doesn't keep the list of blocked sites when you close firefox (53.0.3),
> Secondly it doesn't block sites in the images search section.
> thank you for your work.
>
> firefox (53.0.3)
> OS Windows 10

**Comment by taxen** [comment]
Somehow I lost all blocklist data while maybe updating FF to 55.0.3. I had over 500 blocklist by that time and the damage is huge. Unfortunately, I did not backup any data. With current manual copy/paste style backup is too handful to do frequently. I know the data is stored in SQLite file, webappsstore.sqlite under Profiles/[profile name]/. Will there be simpler way to backup so that users can backup more often and securely?

**Comment by wildskyf** [comment]
Hi @taxen,

I just found my add-on use localStorage to save data.
So it is easily lost under some situation.

I have changed it to use browser.storage. It should be stronger!
Please wait until v2.0.0.

and also thanks for your report!

**Comment by taxen** [comment]
Thank you! I will wait for the next release.

**Comment by taxen** [comment]
I updated to 2.0.0 and found the data is now stored into storage-sync.sqlite under Profiles/[profile name]/. No problem so far. Thank you!
